[package]
name = "cryptohack-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "cryptohack"
path = "src/lib.rs"

[dependencies]
base64 = "0.22.1"
hex = "0.4.3"
num-bigint = "0.4.6"
num-traits = "0.2.19"
